---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
  labels:
    app: hello-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-web
  template:
    metadata:
      labels:
        app: hello-web
    spec:
      containers:
      - name: carl
        image: gcr.io/widgetworld-serverless/carl
        ports:
        - containerPort: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hello-web-service"
  namespace: "default"
  labels:
    app: "hello-web"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "hello-web"
  type: "LoadBalancer"
  loadBalancerIP: ""
